### ISSUE TITLE
Sometimes if startAndroidEmulator fails, waitForAndroidEmulator stuck forever

### ISSUE THREAD

**Issue by neworld** [quittle/gradle-android-emulator#27]
I found it in my docker environment. If I forget to add `--device /dev/kvm` or some dependency, `startAndroidEmulator` will succeed anyway. And then `waitForAndroidEmulator` waits forever, because there is no device. 

I am still looking for a solution. But extra logging and timeout would be nice features.

**Comment by quittle** [comment]
Hi @neworld, I realized a little while ago that this plugin hangs forever on Travis CI and am working to figure out what was wrong. I agree that being able to get the logs from the emulator or timing out how long to wait for would be useful.

Once I figure out the root cause of why it isn't starting, I will update the plugin to expose flags that helped me diagnose the issue. Two you mentioned, logs and a timeout are reasonable. If you want them sooner, feel free to open a pull request with those features.

**Comment by quittle** [comment]
I believe I have found a common reason why the emulator does not start, the `ANDROID_HOME` environment variable now is required for the emulator to start and fails with `PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value` without it. I will try to update the plugin to provide that environment variables first and then work on exposing the emulator output via plugin configuration to help others, like yourself, debug issues.

**Comment by quittle** [comment]
I have now released `v0.0.3` which should includes both the fix and additional logging flags. Can you confirm if this addresses you problems @neworld?

**Comment by neworld** [comment]
`ANDROID_HOME` is one of the problems why AVD failed to run. Another is missing KVM. Your fixes are a big improvement. Thanks! I will test soon. However, one thing is still missing for perfection: `startAndroidEmulator` should fail if AVD failed to start.

**Comment by quittle** [comment]
I can't do it as part of `startAndroidEmulator` because it starts the emulator process separately and I won't know how long to wait. It would make sense to check that the emulator process is still running as part of the `waitForAndroidEmulator` task. I will see if I can get `adb` to detect the emulator is no longer running but likely will have to create a separate thread to monitor the process until the waiting task completes.

**Comment by neworld** [comment]
I suppose `adb` is not able to see the emulator state. It waits until any device is available, and the emulator needs some time to boot until it can communicate with `adb`. Looking for AVD  sounds a good idea.

**Comment by neworld** [comment]
Timeout workaround works pretty well:
```
tasks.whenTaskAdded { task ->
    if (task.name == "waitForAndroidEmulator") {
        task.timeout = Duration.ofMinutes(1)
    }
}
```

**Comment by quittle** [comment]
I don't think this is the correct, long term solution to add into the plugin, though it may work fine for you. Checking that the process was not killed would be the cleanest and fastest way to ensure it's still starting up. I found it can take longer than a minute or two in Travis CI for the emulator to start up because of the ARM emulation. Have you faced any issues before where the emulator process was still running but the emulator itself would never start up?

**Comment by neworld** [comment]
Actually, this workaround is for users to put in their config (if needed) rather than apply this into the plugin. Maybe the plugin could support the `timeout` flag.

**Comment by quittle** [comment]
The above commit should handle aborting early if an issue occurs. I want to clean it up a bit more before landing but should be close to what will ultimately land

**Comment by neworld** [comment]
The commit is very promising.

**Comment by quittle** [comment]
This has landed and should be fixed in release `0.1.1`
